[server]
listen_addr = "127.0.0.1:53"
cache_capacity = 10000

[rules]
enable_cache = true
# nxdomain refused 0.0.0.0
block_mode = "0.0.0.0"
blacklist = [
    "ad.xiaomi.com",
    "track.apple.com",
    "tiktok.com"
]

[[upstreams]]
name = "Aliyun_UDP"
address = "223.5.5.5:53"
protocol = "udp"
timeout_ms = 400

[[upstreams]]
name = "Tencent_UDP"
address = "119.29.29.29:53"
protocol = "udp"
timeout_ms = 400

[[upstreams]]
name = "Google_DoH"
address = "https://dns.google/dns-query"
protocol = "doh"
timeout_ms = 1500

[[upstreams]]
name = "Cloudflare_DoH"
address = "https://1.1.1.1/dns-query"
protocol = "doh"
timeout_ms = 1500

[[upstreams]]
name = "Unicom"
address = "192.168.1.1:53"
protocol = "udp"
timeout_ms = 1500

[[upstreams]]
name = "Telecom-1"
address = "218.85.152.99:53"
protocol = "udp"
timeout_ms = 1500

[[upstreams]]
name = "Telecom-2"
address = "218.85.157.99:53"
protocol = "udp"
timeout_ms = 1500